import type { Message, Session, WorkbenchSnapshot } from '../model/types';
const messages: Message[] = [
  {
    id: 'm1',
    parentId: null,
    role: 'user',
    at: '10:24',
    text: 'The reconnect path still drops the last response. Can you check what changed and add a regression test? Leave the timeout setting alone.',
  },
  {
    id: 'm2',
    parentId: 'm1',
    role: 'assistant',
    at: '10:24',
    text: 'I’ll trace the reconnect handler, compare the previous change, and check how the response buffer is passed to the new connection.',
    thinking:
      'The timeout may be a symptom. First follow the response buffer across the close event and inspect the existing tests.',
  },
  {
    id: 'm3',
    parentId: 'm2',
    role: 'tool',
    at: '10:24',
    text: 'read connection handler',
    tool: {
      id: 'tool1',
      name: 'read_file',
      input: { file_path: 'src/connection.ts', offset: 0, limit: 80 },
      output:
        '1: export function reconnect(session: Session) {\n2:   const pending = session.pending;\n3:   session.close();\n4:   return connect(session.url, { pending });\n5: }',
      status: 'success',
      elapsed: '0.2s',
      filePath: 'src/connection.ts',
    },
  },
  {
    id: 'm4',
    parentId: 'm3',
    role: 'tool',
    at: '10:25',
    text: 'inspect existing tests',
    tool: {
      id: 'tool2',
      name: 'task',
      input: {
        subagent_type: 'explore',
        description: 'Find tests covering reconnect and buffered responses',
      },
      output:
        'The normal reconnect path is covered. The suite has no case where a response arrives between close and the new connection.',
      status: 'success',
      elapsed: '12.4s',
      agentId: 'agent1',
    },
  },
  {
    id: 'm5',
    parentId: 'm4',
    role: 'assistant',
    at: '10:25',
    text: 'The reconnect handler keeps a reference to the old pending buffer. Closing the session can clear that buffer before the new connection receives it.\n\nI’ve prepared a change that snapshots the pending responses, plus a regression case for the close/reconnect boundary. The timeout stays unchanged.\n\nThe changes on the right are **sample data** for reviewing the frontend. No files or commands have been run.',
    usage: { input: 4280, output: 684, cost: null, elapsed: '18.2s' },
  },
  {
    id: 'm6',
    parentId: 'm2',
    role: 'user',
    at: 'yesterday',
    text: 'First show me which tests cover reconnect.',
    label: 'review first',
  },
];
function session(
  id: string,
  title: string,
  workspaceId: string,
  ownMessages: Message[] = messages,
): Session {
  return {
    id,
    title,
    workspaceId,
    model: 'sample-code-model',
    effort: 'high',
    draft: '',
    messages: structuredClone(ownMessages),
    leafId: ownMessages === messages ? 'm5' : (ownMessages.at(-1)?.id ?? null),
    hiddenIds: [],
    undoStack: [],
    attachments: [],
    queue: [],
    state: 'idle',
    readOnly: false,
    auto: false,
    showThinking: true,
    expandTools: false,
    todos:
      ownMessages === messages
        ? [
            {
              id: 'todo1',
              text: 'Trace the response buffer through reconnect',
              status: 'completed',
            },
            {
              id: 'todo2',
              text: 'Add a regression for the close boundary',
              status: 'running',
            },
            {
              id: 'todo3',
              text: 'Review the diff and run the focused tests',
              status: 'pending',
            },
          ]
        : [],
    pinned: id === 'session1',
    shared: false,
    updatedAt: 'today',
  };
}
export function createFixtures(): WorkbenchSnapshot {
  return {
    version: 1,
    activeSessionId: 'session1',
    previousSessionId: null,
    workspaces: [
      {
        id: 'workspace1',
        name: 'orbit-api',
        path: '/workspace/orbit-api',
        branch: 'fix/reconnect',
        trusted: true,
        instructions: [
          {
            name: 'AGENTS.md',
            content:
              '# project instructions\n\nKeep changes scoped. Add a regression for every behavior change. Preserve raw tool results.\n\nSynthetic frontend fixture.',
          },
          {
            name: '.circle/settings.json',
            content: '{"default_thinking":"high"}',
          },
        ],
      },
      {
        id: 'workspace2',
        name: 'docs-site',
        path: '/workspace/docs-site',
        branch: 'main',
        trusted: false,
        instructions: [
          {
            name: 'AGENTS.md',
            content: 'Check links and preserve code examples.',
          },
        ],
      },
    ],
    sessions: [
      session('session1', 'Fix the reconnect race', 'workspace1'),
      session('session2', 'Review the request lifecycle', 'workspace1', [
        {
          id: 'review1',
          parentId: null,
          role: 'user',
          at: 'yesterday',
          text: 'Check whether the lifecycle guide matches the code.',
        },
        {
          id: 'review2',
          parentId: 'review1',
          role: 'assistant',
          at: 'yesterday',
          text: 'I can compare the guide with the implementation once a runtime is connected.',
        },
      ]),
      session('session3', 'Tighten the setup guide', 'workspace2', []),
    ],
    files: [
      {
        id: 'file1',
        workspaceId: 'workspace1',
        path: 'src/connection.ts',
        language: 'typescript',
        original:
          'export function reconnect(session: Session) {\n  const pending = session.pending;\n  session.close();\n  return connect(session.url, { pending });\n}\n',
        content:
          'export function reconnect(session: Session) {\n  const pending = [...session.pending];\n  session.close();\n  return connect(session.url, { pending });\n}\n',
        status: 'modified',
      },
      {
        id: 'file2',
        workspaceId: 'workspace1',
        path: 'tests/reconnect.test.ts',
        language: 'typescript',
        original: '',
        content:
          "test('preserves a response across reconnect', () => {\n  const session = makeSession();\n  session.pending.push('response');\n  const next = reconnect(session);\n  expect(next.pending).toEqual(['response']);\n});\n",
        status: 'added',
      },
      {
        id: 'file3',
        workspaceId: 'workspace1',
        path: 'README.md',
        language: 'markdown',
        content:
          '# orbit-api\n\nA sample project for the Circle workbench.\nNo runtime or network connection is attached.\n',
      },
      {
        id: 'file4',
        workspaceId: 'workspace1',
        path: 'package.json',
        language: 'json',
        content:
          '{"name":"orbit-api","private":true,"scripts":{"test":"vitest run"}}',
      },
      {
        id: 'file5',
        workspaceId: 'workspace2',
        path: 'guide.md',
        language: 'markdown',
        content: '# setup\n\nChoose an endpoint, then select a model.\n',
      },
    ],
    agents: [
      {
        id: 'agent1',
        sessionId: 'session1',
        name: 'explore',
        description: 'Find reconnect coverage',
        status: 'completed',
        model: 'sample-fast-model',
        tokens: 2610,
        messages: [
          {
            id: 'a1',
            parentId: null,
            role: 'assistant',
            at: '10:24',
            text: 'Looking for reconnect and pending-buffer tests.',
          },
          {
            id: 'a2',
            parentId: 'a1',
            role: 'tool',
            at: '10:24',
            text: 'find reconnect tests',
            tool: {
              id: 'at1',
              name: 'grep',
              input: { pattern: 'reconnect', path: 'tests' },
              output:
                'tests/reconnect.test.ts: normal reconnect\ntests/session.test.ts: closes pending buffer',
              status: 'success',
            },
          },
          {
            id: 'a3',
            parentId: 'a2',
            role: 'assistant',
            at: '10:25',
            text: 'The close/reconnect boundary is not covered by the sample tests.',
          },
        ],
      },
      {
        id: 'agent2',
        sessionId: 'session1',
        name: 'general-purpose',
        description: 'Review the proposed regression',
        status: 'waiting',
        model: 'sample-code-model',
        tokens: 1180,
        messages: [
          {
            id: 'a4',
            parentId: null,
            role: 'assistant',
            at: '10:26',
            text: 'Waiting for a test-command approval in this sample record.',
          },
        ],
      },
    ],
    jobs: [
      {
        id: 'j1',
        sessionId: 'session1',
        kind: 'command',
        title: 'npm run test -- reconnect',
        state: 'running',
        elapsed: '14s',
        output:
          '> vitest run reconnect\n\nRUN sample test session\nwaiting for runtime connection\n',
        outputPath: 'preview/background_jobs/j1.log',
        stopRequested: false,
      },
      {
        id: 'j2',
        sessionId: 'session1',
        kind: 'agent',
        title: 'Review the proposed regression',
        state: 'waiting',
        elapsed: '9s',
        output: 'Read tests/reconnect.test.ts\nwaiting for you',
        outputPath: 'preview/background_jobs/j2.log',
        stopRequested: false,
        agentId: 'agent2',
      },
      {
        id: 'j3',
        sessionId: 'session2',
        kind: 'watch',
        title: 'Wait for documentation build',
        state: 'completed',
        elapsed: '6s',
        output: 'sample build finished',
        outputPath: 'preview/background_jobs/j3.log',
        stopRequested: false,
      },
    ],
    interactions: [
      {
        id: 'approval1',
        sessionId: 'session1',
        kind: 'approval',
        title: 'execute needs your permission',
        tool: 'execute',
        command: 'npm run test -- reconnect',
        target: '/workspace/orbit-api',
        status: 'pending',
        revision: 1,
      },
      {
        id: 'question1',
        sessionId: 'session1',
        kind: 'question',
        title: 'Which versions should the regression cover?',
        choices: ['current release', 'current and previous release'],
        multiple: true,
        status: 'pending',
        revision: 1,
      },
      {
        id: 'plan1',
        sessionId: 'session1',
        kind: 'plan-exit',
        title: 'Ready to implement this plan?',
        status: 'pending',
        revision: 1,
      },
      {
        id: 'secret1',
        sessionId: 'session1',
        kind: 'secret',
        title: 'deployment token',
        target: 'preview/.env.local',
        status: 'pending',
        revision: 1,
      },
    ],
    approvalRules: [
      {
        id: 'rule1',
        sessionId: 'session1',
        kind: 'command',
        description: 'npm run lint',
      },
      {
        id: 'rule2',
        sessionId: 'session1',
        kind: 'tool',
        description: 'docs_search',
      },
    ],
    models: [
      {
        id: 'sample-code-model',
        provider: 'sample endpoint',
        contextWindow: 128000,
        inputPrice: null,
        outputPrice: null,
        vision: true,
      },
      {
        id: 'sample-fast-model',
        provider: 'sample endpoint',
        contextWindow: 64000,
        inputPrice: null,
        outputPrice: null,
        vision: false,
      },
      {
        id: 'sample-review-model',
        provider: 'sample endpoint',
        contextWindow: 200000,
        inputPrice: null,
        outputPrice: null,
        vision: true,
      },
    ],
    skills: [
      {
        id: 'skill1',
        name: 'code-review',
        description: 'Review code changes and record concrete findings.',
        path: '.agents/skills/code-review/SKILL.md',
        scope: 'project',
        content:
          '# code review\n\nRead the patch and its callers. Explain concrete failures, cite the relevant code, and list missing evidence.',
      },
      {
        id: 'skill2',
        name: 'regression-tests',
        description: 'Turn a reproducible failure into a focused regression.',
        path: '~/.circle/skills/regression-tests/SKILL.md',
        scope: 'user',
        content:
          '# regression tests\n\nReproduce the failure before changing the implementation. Check the observable result, not only the internal flag.',
      },
    ],
    commands: [
      {
        name: 'review',
        description: 'Review the current changes',
        arguments: '[focus]',
        scope: 'project',
        template: 'Review the current changes. Focus on $ARGUMENTS.',
      },
      {
        name: 'release-notes',
        description: 'Draft release notes',
        arguments: '<version>',
        scope: 'user',
        template: 'Draft release notes for $1.',
      },
      {
        name: 'hello',
        description: 'A sample extension command',
        arguments: '[name]',
        scope: 'extension',
        template: 'Hello $ARGUMENTS',
      },
    ],
    mcp: [
      {
        id: 'mcp1',
        name: 'docs',
        transport: 'streamable_http',
        command: '',
        args: '',
        url: 'https://docs.example.test/mcp',
        enabled: true,
        status: 'sample',
        tools: [
          {
            name: 'docs_search',
            description: 'Search the sample documentation',
            schema: {
              type: 'object',
              properties: { query: { type: 'string' } },
            },
          },
        ],
      },
      {
        id: 'mcp2',
        name: 'workspace',
        transport: 'stdio',
        command: 'sample-mcp',
        args: '--read-only',
        url: '',
        enabled: false,
        status: 'not connected',
        tools: [],
        error: 'runtime connection required',
      },
    ],
    extensions: [
      {
        id: 'extension1',
        name: 'review-tools',
        version: '0.1.0',
        scope: 'project',
        enabled: true,
        tools: ['review_note'],
        commands: ['hello'],
        events: ['session_start', 'tool_result'],
      },
      {
        id: 'extension2',
        name: 'sample-failing-extension',
        version: '0.1.0',
        scope: 'user',
        enabled: false,
        tools: [],
        commands: [],
        events: [],
        error: 'sample load error: duplicate tool name',
      },
    ],
    requests: [],
    settings: {
      theme: 'auto',
      hideThinking: false,
      defaultModel: 'sample-code-model',
      defaultEffort: 'high',
      enabledModels: [],
      doubleEscape: 'tree',
      endpoint: 'https://api.example.test/v1',
      protocol: 'openai',
      credentialFiles: ['*.key'],
      updateCheck: true,
      uiFontSize: 13,
      codeFontSize: 13,
      keybindings: {},
    },
    uiPlugins: [
      'files',
      'activity',
      'browser',
      'knowledge',
      'work',
      'execution',
      'methods',
    ],
  };
}
